{
	"Name": "Project Fireworks",
	"Version": "4.9.3.0",
	"Assemblies":
	[
		{
			"Path": "/Fireworks.dll",
			"Role": "Server"
		},
		{
			"Path": "/Rocket.API.dll",
			"Role": "Server"
		},
		{
			"Path": "/Rocket.Core.dll",
			"Role": "Server"
		},
		{
			"Path": "/Rocket.Unturned.dll",
			"Role": "Server"
		}
	],
	"Dependencies":
	[
		{
			"Name": "Framework",
			"Version": "3.17.4.0"
		},
		{
			"Name": "Unturned",
			"Version": "3.17.4.0"
		},
		{
			"Name": "PointBlank",
			"Version": "1.0.0.0"
		}
	]
}
